spring:
  application:
   name: springbootproject
  data:
   redis:
      host: redis-18048.c330.asia-south1-1.gce.redns.redis-cloud.com
      port: 18048
      username: --------------------
      password: --------------------
      #host: localhost
      #port: 6379
   mongodb:
      uri: -----------------
      database: journaldb
      auto-index-creation: true
  mail:
   host: smtp.gmail.com
   port: 587
   username: ---------
   password: ------------
   to: -------------
   cc: ---------------
   properties:
      mail:
       smtp:
        auth: true
        starttls:
         enable: true
   
server:
  port: 8080
api:
 weather:
  key: --------------------

